### ISSUE TITLE
Quick search box for a user's character list

### ISSUE THREAD

**Issue by Throne3d** [glowfic-constellation/glowfic#1130]
Since we now paginate character lists, it'd be cool to have a quick search up top (like the users list) that redirects to the character search page with the right user ID filled and the name entered in the form.

This way, we preserve workflows where people used to Ctrl+F for specific characters.

(I've marked this high priority because we want to try to avoid impacting existing workflows.)

**Comment by teceler** [comment]
Mostly fixed by #1160, but that search does not include template names.
