### ISSUE TITLE
Add performance gems

### ISSUE THREAD

**Issue by Throne3d** [glowfic-constellation/glowfic#22]
> Listed here http://www.akitaonrails.com/2016/03/22/is-your-rails-app-ready-for-production

> For gems, look into RackAttack and RackProtection - sprockets should come free with Rails 4.2+ and RackCache should be done with a CDN.
On which note, install Cloudfront into Heroku to serve static assets.
Also, look into Sidekiq vs Celery (suspect Sidekiq)

**Comment by Marri** [comment]
This should definitely wait until we sort out memory; gems take memory.

**Comment by Throne3d** [comment]
Not a huge issue anymore, we have NewRelic and Scout and stuff and can investigate these prod gems later (esp since recommendations are likely v different from what they were 5 years ago)
