### ISSUE TITLE
Indexes and collections, distinct from continuities

### ISSUE THREAD

**Issue by Throne3d** [glowfic-constellation/glowfic#295]
Requested [here](http://alicorn.elcenia.com/board/viewtopic.php?f=12&t=459&start=2310#p34126) by Alicorn, something that "worked mechanically exactly like a continuity except a) not being called that ("an index"?) and b) allowing threads to be in more than one of them. Possibly also c) the ability to add threads to them without being involved in creating the thread".

**Comment by dhouck** [comment]
This way the Particularly Good Threads section on Alicornutopia could be moved to a Constellation index.

Unfortunately, I don’t think it would be reasonable to make it smart enough to autogenerate author indexes, since those often contain information not available in other metadata.

**Comment by Throne3d** [comment]
We'd need to have freely-editable indexes for that, I think? (Unless there's some meta post to suggest them in.) It'd also need some way to attach a little index-specific summary to the post, which current continuities don't have.

**Comment by Throne3d** [comment]
Indexes were added in #519
