### ISSUE TITLE
Seed data should try to cover more scenarios

### ISSUE THREAD

**Issue by Throne3d** [glowfic-constellation/glowfic#416]
- [x] Have various tags, have them attached to things in varying quantities (character settings, post tags, gallery groups)
- [ ] Have some uploaded icons, maybe? (Could be hard to do without accidentally deleting real icons at some point)
- [x] Have posts, replies, boards, board sections, of varying kinds and with various descriptions and showcasing various things
- [x] Add throne as a seed user because he messes with examples all the time

Try to keep this under the hobby row count (probably quite a bit under it if doable). Maybe import a dreamwidth thread or two and a current Constellation thread or two.

(Keywords: seeds)

**Comment by teceler** [comment]
We probably do not need all the various icons and characters that is currently has, too, just a subset of that.

**Comment by teceler** [comment]
All resolved except uploaded icons, which are Difficult at present (tho ActiveStorage might solve this) in #1134 and #1149
