### ISSUE TITLE
NPC box

### ISSUE THREAD

**Issue by Throne3d** [glowfic-constellation/glowfic#425]
Probably done with aliases on the main user account that then display. This makes it lower barrier to add accounts for NPCs, since they won't show up in your large list of characters and you don't need to facecast them or anything, but you can still name them to make it clear who's who.

There should be a way to then convert your NPC posts into an actual character (characters#replace on main user account in specific posts with a specific alias?).

This likely relies on alias creation being made easier (in the reply editor or at least faster on the character page) – #171.

**Comment by echurilov** [comment]
I think I don't understand enough about the code yet to know where I'd start, but this sounds like a cool feature. I'd like to come back and see about working on this once I know more about aliases.

**Comment by Throne3d** [comment]
https://discord.com/channels/521407923629457428/521407923629457431/1155296808482897930
