### ISSUE TITLE
Add setup steps to bin/setup and mention it in the README

### ISSUE THREAD

**Issue by Throne3d** [glowfic-constellation/glowfic#458]
From Rails 4.2, there's a new `bin/setup` file that has some defaults for what to install to get up and running quickly. We could add some of the other steps from the README to that to automate the setup process, if we want.

**Comment by Marri** [comment]
We could add the Heroku remotes, but I'm not sure how much else there is to add tbh? So much of the setup guide is pre-reqs to getting to bin/setup, like having Postgres installed, and we can't include that without a) much more bash knowledge or b) locking us to an OS

**Comment by Throne3d** [comment]
Checking for Ubuntu should be relatively straightforward in Bash – check the result of `uname -a` contains `Ubuntu`? (I'd have to check it on the machine to see if it has that exact string, but it should be included there somewhere.)

We could do that for Arch and Ubuntu and then probably figure out something for macOS, and install the relevant packages using (respectively) pacman, apt-get and homebrew? It might be too much effort for little gain. I'm not sure what usually goes into it, but also: creating, migrating, and seeding the database would be good – I think it might already do that?

**Comment by Throne3d** [comment]
Most stuff is handled here
