### ISSUE TITLE
Reply search dropdowns should be filtered by javascript

### ISSUE THREAD

**Issue by Throne3d** [glowfic-constellation/glowfic#64]
- [X] When an author is selected, only show their templates/characters  
- [ ] When a template is selected, only show its characters  
- [X] When a continuity or thread is selected, only show its authors/templates/characters

Currently the list is superhuge and can lag the browser when on the page.

**Comment by Marri** [comment]
When an author is selected, show only their templates was fixed in #364, and we fixed the superhuge browser lag thing with some of the memory work. Still remaining: filter characters by template/author.

**Comment by Throne3d** [comment]
Probably good enough as-is
