### ISSUE TITLE
Resque and retry handling

### ISSUE THREAD

**Issue by Throne3d** [glowfic-constellation/glowfic#66]
> * Come up with a way to test the retry handling, I think there's resque_rspec?
> * Do retries better so they're not infinite, see [resque-retry](https://github.com/lantins/resque-retry)
> 
> I see multiple copies of post id 452 in the queue, something is off
>
> Deploys are causing long running background jobs to crash. I'm supposed to be catching sigterms, don't do that.

**Comment by Marri** [comment]
resque-retry and resque_rspec are done, just for historical note; still need to do the other two

**Comment by Throne3d** [comment]
Deploys crash jobs again (still?), which needs to be fixed. Retrying might not be working? I forget what I did around that. It'd be a good idea to look into this soon.
