### ISSUE TITLE
Threadnotes system

### ISSUE THREAD

**Issue by Throne3d** [glowfic-constellation/glowfic#689]
It would be useful to keep track of TODOs, plot ideas, upcoming events and whatnot, for individual threads/posts. This would presumably be shown when you're constructing a reply, and might be shareable between coauthors.

If notes are implemented for posts, it might be worth considering a more general notes system (for characters having potential developments, or for stuff you don't want to make public about your settings). This might, however, make it harder to integrate the system so tightly and have it be useful in specific ways that [other generic notes service] isn't.

**Comment by Throne3d** [comment]
More feedback:

- It would be nice if these stored a history
- It would be nice if they could be shared between coauthors
- It would be nice if, when opening the post to reply, it showed "New!" on the "bring up the notes menu" system

For a basic implementation, I think the things we want are:

- when replying, there is some way to bring up a notes section for the thread, shared between authors
- you can edit this, presumably with an editor in either HTML or RTF mode
- you must press "save" to save it
- (optionally) you are notified if you try to leave or exit without saving
- (more optionally) it keeps track of history in audits
- (even more optionally) if there is a conflict with someone else having edited it, it shows you their copy versus your copy, or maybe diffs it, or something, and you can re-edit and save
- (further optionally) it keeps track of when you last viewed it, and displays "New!" if it's been edited since then, so you can keep up to date with it changing over time

The last in the list allows things like leaving coauthors messages of "can you let me know if this isn't going to achieve the right response?" when writing High Charisma characters, or "maybe a tag – does your character want to jump in here?" or "still self-threading", though these last two could make be saved otherwise.

**Comment by echurilov** [comment]
This sounds pretty exciting and I'd be interested in working on it once I'm more familiar with the code, and maybe if someone is free to pair with me, since it seems like the scope is pretty big?

**Comment by Throne3d** [comment]
Done in #1295
