### ISSUE TITLE
List of browsers and version supported

### ISSUE THREAD

**Issue by Throne3d** [glowfic-constellation/glowfic#86]
Should go somewhere near patch notes (#54) or the help menu (#78).

> Safari <9 does not support .startsWith() which was breaking the character and icon swap functions when posting. I should actually list somewhere what browsers and versions are supported so people are aware that this could be a cause. -Marri

> Maybe distinguish between ones that we expect should work, and ones that we expect to *keep* working. I guess that's what 'supported' means.
> I don't think I care too much about IE8 and below? -Throne

**Comment by Throne3d** [comment]
I'm assuming we're supporting at least Chrome 50+, Firefox 50+, possibly Microsoft Edge and maybe some versions of Safari? Plus Android stock browser, Chrome on Android, Firefox on Android, Safari on iOS…?

**Comment by Throne3d** [comment]
We should probably at least come up with a preliminary list.

We could also start using lodash or underscore.js or some polyfills / shims / whatever to add better backwards compatibility to our JavaScript (and allow us to completely disregard the fact our JavaScript might be making use of extremely recent useful tools).

**Comment by teceler** [comment]
Hm, we probably need a way to test older browser versions? Granted 'people report a bug' is a way, but seems suboptimal.

Wrt more current ones, I can test chromium (which is basically chrome) and firefox... 56.0 (currently frozen there until the upgrade is less of a disaster). And android stock browser, though that'll need things loaded to staging (theoretically I could also test firefox and chrome on android, and I'll look into it if neither of you can).

**Comment by Throne3d** [comment]
My proposed list:
- Chrome 60+
- Firefox 52 ESR, 60+
- Microsoft Edge 16+
- Safari 10+
- Safari & Chrome for iOS 9.3+
- Android stock browser 4.4+
- Chrome Android 67+
- Firefox Android 60+

Made by looking (non-principledly) at the release dates and global usage in <https://caniuse.com/#search=border-radius>.

**Comment by Throne3d** [comment]
As of 2021-12-22, what we decided on was:
- Chrome evergreen (96+ is current)
- Firefox evergreen (95+ is current, ESR 91+)
- Microsoft Edge evergreen (96+ is current, based on Chromium)
- Safari 11+ (supports ES6 + let/const)
- Safari & Chrome for iOS 11+ (supports ES6 + let/const)
- Chrome Android, combined with Android stock browser, evergreen (96+ is current)
- Firefox Android evergreen (95+ is current)

We probably only want to support the latest e.g. 3 versions of the evergreen browsers, and just tell people to upgrade otherwise.

Seems like we're good here.
